import { api } from "@/services/http/client";

export type ScaleReadiness = {
  spaceId: string;
  memorySchemaVersion: number;
  memoryApprovedCount: number;
  runRunningCount?: number;
  runWaitingApprovalCount?: number;
  runInflightCount?: number;
  ragDocumentCount: number;
  ragChunkCount: number;
  modelUsageRows: number;
  modelCostMicrosTotal: number;
  qualityMetricRows: number;
  auditLogRows: number;
  databaseDialect?: string;
  postgresConfigured?: boolean;
  migrationReady?: boolean;
  sqlitePath?: string;
  migrationTableCount?: number;
  dualWriteEnabled?: boolean;
  dualWriteRuntime?: boolean;
  dualWriteSource?: string;
  lastMigrationSyncAtMs?: number;
  lastMigrationSyncError?: string;
  lastMigrationSyncErrorAtMs?: number;
  postgresRLSEnabled?: boolean;
  postgresRLSForce?: boolean;
  postgresRLSPolicyCount?: number;
  postgresRLSPolicyExpected?: number;
  rlsCatalogSummary?: string;
  postgresAppUrlConfigured?: boolean;
  workerConnectionRole?: string;
  runtimeDsnHint?: string;
  dualWriteShadowUrlHint?: string;
  schemaMode?: string;
  sqlMigrationsEnabled?: boolean;
  autoMigrateEnabled?: boolean;
  sqlMigrationVersion?: number;
  sqlMigrationExpected?: number;
  readinessWarnings?: string[];
  memoryCatalogVersion?: number;
  memoryPendingMigrationRecords?: number;
  memoryTTLReviewDueCount?: number;
  memoryTTLExpiredPendingCount?: number;
  memoryTTLReviewLeadDays?: number;
  ragFtsAvailable?: boolean;
  ragFtsEngine?: string;
  ragDefaultRetrievalMode?: string;
  ragFallbackQueryCount?: number;
  otelEnabled?: boolean;
  alertsEvalInterval?: string;
  memoryTTLSweepInterval?: string;
  metricsEventReplayEnabled?: boolean;
  retentionEventsDays?: number;
  retentionAuditDays?: number;
  retentionArtifactsDays?: number;
  retentionArtifactsMaxRuns?: number;
};

export function getScaleReadiness() {
  return api<ScaleReadiness>("/scale/readiness");
}
