// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ash/v1/plugin_registry.proto

package ashv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Protocol        string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Abi             string                 `protobuf:"bytes,5,opt,name=abi,proto3" json:"abi,omitempty"`
	Endpoint        string                 `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Capabilities    []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	SupportedEvents []string               `protobuf:"bytes,8,rep,name=supported_events,json=supportedEvents,proto3" json:"supported_events,omitempty"`
	Context         *TraceContext          `protobuf:"bytes,9,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_ash_v1_plugin_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ash_v1_plugin_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_ash_v1_plugin_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RegisterRequest) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

func (x *RegisterRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetSupportedEvents() []string {
	if x != nil {
		return x.SupportedEvents
	}
	return nil
}

func (x *RegisterRequest) GetContext() *TraceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Compatible    bool                   `protobuf:"varint,2,opt,name=compatible,proto3" json:"compatible,omitempty"`
	PluginId      string                 `protobuf:"bytes,3,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Status        *Status                `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_ash_v1_plugin_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ash_v1_plugin_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_ash_v1_plugin_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetCompatible() bool {
	if x != nil {
		return x.Compatible
	}
	return false
}

func (x *RegisterResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *RegisterResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Context       *TraceContext          `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_ash_v1_plugin_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ash_v1_plugin_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_ash_v1_plugin_registry_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *HeartbeatRequest) GetContext() *TraceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_ash_v1_plugin_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ash_v1_plugin_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_ash_v1_plugin_registry_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Context       *TraceContext          `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_ash_v1_plugin_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ash_v1_plugin_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_ash_v1_plugin_registry_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatusRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *GetStatusRequest) GetContext() *TraceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Compatible    bool                   `protobuf:"varint,3,opt,name=compatible,proto3" json:"compatible,omitempty"`
	Status        *Status                `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_ash_v1_plugin_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ash_v1_plugin_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_ash_v1_plugin_registry_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *GetStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetStatusResponse) GetCompatible() bool {
	if x != nil {
		return x.Compatible
	}
	return false
}

func (x *GetStatusResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_ash_v1_plugin_registry_proto protoreflect.FileDescriptor

const file_ash_v1_plugin_registry_proto_rawDesc = "" +
	"\n" +
	"\x1cash/v1/plugin_registry.proto\x12\x06ash.v1\x1a\x13ash/v1/common.proto\"\x98\x02\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03abi\x18\x05 \x01(\tR\x03abi\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x12)\n" +
	"\x10supported_events\x18\b \x03(\tR\x0fsupportedEvents\x12.\n" +
	"\acontext\x18\t \x01(\v2\x14.ash.v1.TraceContextR\acontext\"\x93\x01\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1e\n" +
	"\n" +
	"compatible\x18\x02 \x01(\bR\n" +
	"compatible\x12\x1b\n" +
	"\tplugin_id\x18\x03 \x01(\tR\bpluginId\x12&\n" +
	"\x06status\x18\x04 \x01(\v2\x0e.ash.v1.StatusR\x06status\"_\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12.\n" +
	"\acontext\x18\x02 \x01(\v2\x14.ash.v1.TraceContextR\acontext\"K\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12&\n" +
	"\x06status\x18\x02 \x01(\v2\x0e.ash.v1.StatusR\x06status\"_\n" +
	"\x10GetStatusRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12.\n" +
	"\acontext\x18\x02 \x01(\v2\x14.ash.v1.TraceContextR\acontext\"\x8e\x01\n" +
	"\x11GetStatusResponse\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1e\n" +
	"\n" +
	"compatible\x18\x03 \x01(\bR\n" +
	"compatible\x12&\n" +
	"\x06status\x18\x04 \x01(\v2\x0e.ash.v1.StatusR\x06status2\xda\x01\n" +
	"\x15PluginRegistryService\x12=\n" +
	"\bRegister\x12\x17.ash.v1.RegisterRequest\x1a\x18.ash.v1.RegisterResponse\x12@\n" +
	"\tHeartbeat\x12\x18.ash.v1.HeartbeatRequest\x1a\x19.ash.v1.HeartbeatResponse\x12@\n" +
	"\tGetStatus\x12\x18.ash.v1.GetStatusRequest\x1a\x19.ash.v1.GetStatusResponseB/Z-github.com/ash-repwiki/ash/proto/ash/v1;ashv1b\x06proto3"

var (
	file_ash_v1_plugin_registry_proto_rawDescOnce sync.Once
	file_ash_v1_plugin_registry_proto_rawDescData []byte
)

func file_ash_v1_plugin_registry_proto_rawDescGZIP() []byte {
	file_ash_v1_plugin_registry_proto_rawDescOnce.Do(func() {
		file_ash_v1_plugin_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ash_v1_plugin_registry_proto_rawDesc), len(file_ash_v1_plugin_registry_proto_rawDesc)))
	})
	return file_ash_v1_plugin_registry_proto_rawDescData
}

var file_ash_v1_plugin_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ash_v1_plugin_registry_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: ash.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 1: ash.v1.RegisterResponse
	(*HeartbeatRequest)(nil),  // 2: ash.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: ash.v1.HeartbeatResponse
	(*GetStatusRequest)(nil),  // 4: ash.v1.GetStatusRequest
	(*GetStatusResponse)(nil), // 5: ash.v1.GetStatusResponse
	(*TraceContext)(nil),      // 6: ash.v1.TraceContext
	(*Status)(nil),            // 7: ash.v1.Status
}
var file_ash_v1_plugin_registry_proto_depIdxs = []int32{
	6, // 0: ash.v1.RegisterRequest.context:type_name -> ash.v1.TraceContext
	7, // 1: ash.v1.RegisterResponse.status:type_name -> ash.v1.Status
	6, // 2: ash.v1.HeartbeatRequest.context:type_name -> ash.v1.TraceContext
	7, // 3: ash.v1.HeartbeatResponse.status:type_name -> ash.v1.Status
	6, // 4: ash.v1.GetStatusRequest.context:type_name -> ash.v1.TraceContext
	7, // 5: ash.v1.GetStatusResponse.status:type_name -> ash.v1.Status
	0, // 6: ash.v1.PluginRegistryService.Register:input_type -> ash.v1.RegisterRequest
	2, // 7: ash.v1.PluginRegistryService.Heartbeat:input_type -> ash.v1.HeartbeatRequest
	4, // 8: ash.v1.PluginRegistryService.GetStatus:input_type -> ash.v1.GetStatusRequest
	1, // 9: ash.v1.PluginRegistryService.Register:output_type -> ash.v1.RegisterResponse
	3, // 10: ash.v1.PluginRegistryService.Heartbeat:output_type -> ash.v1.HeartbeatResponse
	5, // 11: ash.v1.PluginRegistryService.GetStatus:output_type -> ash.v1.GetStatusResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ash_v1_plugin_registry_proto_init() }
func file_ash_v1_plugin_registry_proto_init() {
	if File_ash_v1_plugin_registry_proto != nil {
		return
	}
	file_ash_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ash_v1_plugin_registry_proto_rawDesc), len(file_ash_v1_plugin_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ash_v1_plugin_registry_proto_goTypes,
		DependencyIndexes: file_ash_v1_plugin_registry_proto_depIdxs,
		MessageInfos:      file_ash_v1_plugin_registry_proto_msgTypes,
	}.Build()
	File_ash_v1_plugin_registry_proto = out.File
	file_ash_v1_plugin_registry_proto_goTypes = nil
	file_ash_v1_plugin_registry_proto_depIdxs = nil
}
