// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ash/v1/rag_indexer.proto

package ashv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *TraceContext          `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	RepoRoot      string                 `protobuf:"bytes,2,opt,name=repo_root,json=repoRoot,proto3" json:"repo_root,omitempty"`
	Embed         bool                   `protobuf:"varint,3,opt,name=embed,proto3" json:"embed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRepoRequest) Reset() {
	*x = IndexRepoRequest{}
	mi := &file_ash_v1_rag_indexer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRepoRequest) ProtoMessage() {}

func (x *IndexRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ash_v1_rag_indexer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRepoRequest.ProtoReflect.Descriptor instead.
func (*IndexRepoRequest) Descriptor() ([]byte, []int) {
	return file_ash_v1_rag_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *IndexRepoRequest) GetContext() *TraceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *IndexRepoRequest) GetRepoRoot() string {
	if x != nil {
		return x.RepoRoot
	}
	return ""
}

func (x *IndexRepoRequest) GetEmbed() bool {
	if x != nil {
		return x.Embed
	}
	return false
}

type IndexRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     int32                  `protobuf:"varint,1,opt,name=documents,proto3" json:"documents,omitempty"`
	Chunks        int32                  `protobuf:"varint,2,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Embedded      int32                  `protobuf:"varint,3,opt,name=embedded,proto3" json:"embedded,omitempty"`
	Status        *Status                `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRepoResponse) Reset() {
	*x = IndexRepoResponse{}
	mi := &file_ash_v1_rag_indexer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRepoResponse) ProtoMessage() {}

func (x *IndexRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ash_v1_rag_indexer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRepoResponse.ProtoReflect.Descriptor instead.
func (*IndexRepoResponse) Descriptor() ([]byte, []int) {
	return file_ash_v1_rag_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *IndexRepoResponse) GetDocuments() int32 {
	if x != nil {
		return x.Documents
	}
	return 0
}

func (x *IndexRepoResponse) GetChunks() int32 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

func (x *IndexRepoResponse) GetEmbedded() int32 {
	if x != nil {
		return x.Embedded
	}
	return 0
}

func (x *IndexRepoResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type QueryRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Context  *TraceContext          `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	RepoRoot string                 `protobuf:"bytes,2,opt,name=repo_root,json=repoRoot,proto3" json:"repo_root,omitempty"`
	Text     string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	TopK     int32                  `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	// "" | path | symbol | text | vector | hybrid+vector
	Prefer        string `protobuf:"bytes,5,opt,name=prefer,proto3" json:"prefer,omitempty"`
	ExpandRefs    bool   `protobuf:"varint,6,opt,name=expand_refs,json=expandRefs,proto3" json:"expand_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_ash_v1_rag_indexer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ash_v1_rag_indexer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_ash_v1_rag_indexer_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetContext() *TraceContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *QueryRequest) GetRepoRoot() string {
	if x != nil {
		return x.RepoRoot
	}
	return ""
}

func (x *QueryRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *QueryRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *QueryRequest) GetPrefer() string {
	if x != nil {
		return x.Prefer
	}
	return ""
}

func (x *QueryRequest) GetExpandRefs() bool {
	if x != nil {
		return x.ExpandRefs
	}
	return false
}

type QueryHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	StartLine     int32                  `protobuf:"varint,4,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine       int32                  `protobuf:"varint,5,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	Digest        string                 `protobuf:"bytes,6,opt,name=digest,proto3" json:"digest,omitempty"`
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`
	Snippet       string                 `protobuf:"bytes,8,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryHit) Reset() {
	*x = QueryHit{}
	mi := &file_ash_v1_rag_indexer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHit) ProtoMessage() {}

func (x *QueryHit) ProtoReflect() protoreflect.Message {
	mi := &file_ash_v1_rag_indexer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHit.ProtoReflect.Descriptor instead.
func (*QueryHit) Descriptor() ([]byte, []int) {
	return file_ash_v1_rag_indexer_proto_rawDescGZIP(), []int{3}
}

func (x *QueryHit) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *QueryHit) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *QueryHit) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *QueryHit) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *QueryHit) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *QueryHit) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *QueryHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QueryHit) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type QueryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Items           []*QueryHit            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	RetrievalMode   string                 `protobuf:"bytes,2,opt,name=retrieval_mode,json=retrievalMode,proto3" json:"retrieval_mode,omitempty"`
	FtsAvailable    bool                   `protobuf:"varint,3,opt,name=fts_available,json=ftsAvailable,proto3" json:"fts_available,omitempty"`
	VectorAvailable bool                   `protobuf:"varint,4,opt,name=vector_available,json=vectorAvailable,proto3" json:"vector_available,omitempty"`
	VectorFallback  string                 `protobuf:"bytes,5,opt,name=vector_fallback,json=vectorFallback,proto3" json:"vector_fallback,omitempty"`
	PreferApplied   string                 `protobuf:"bytes,6,opt,name=prefer_applied,json=preferApplied,proto3" json:"prefer_applied,omitempty"`
	Status          *Status                `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_ash_v1_rag_indexer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ash_v1_rag_indexer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_ash_v1_rag_indexer_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResponse) GetItems() []*QueryHit {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *QueryResponse) GetRetrievalMode() string {
	if x != nil {
		return x.RetrievalMode
	}
	return ""
}

func (x *QueryResponse) GetFtsAvailable() bool {
	if x != nil {
		return x.FtsAvailable
	}
	return false
}

func (x *QueryResponse) GetVectorAvailable() bool {
	if x != nil {
		return x.VectorAvailable
	}
	return false
}

func (x *QueryResponse) GetVectorFallback() string {
	if x != nil {
		return x.VectorFallback
	}
	return ""
}

func (x *QueryResponse) GetPreferApplied() string {
	if x != nil {
		return x.PreferApplied
	}
	return ""
}

func (x *QueryResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_ash_v1_rag_indexer_proto protoreflect.FileDescriptor

const file_ash_v1_rag_indexer_proto_rawDesc = "" +
	"\n" +
	"\x18ash/v1/rag_indexer.proto\x12\x06ash.v1\x1a\x13ash/v1/common.proto\"u\n" +
	"\x10IndexRepoRequest\x12.\n" +
	"\acontext\x18\x01 \x01(\v2\x14.ash.v1.TraceContextR\acontext\x12\x1b\n" +
	"\trepo_root\x18\x02 \x01(\tR\brepoRoot\x12\x14\n" +
	"\x05embed\x18\x03 \x01(\bR\x05embed\"\x8d\x01\n" +
	"\x11IndexRepoResponse\x12\x1c\n" +
	"\tdocuments\x18\x01 \x01(\x05R\tdocuments\x12\x16\n" +
	"\x06chunks\x18\x02 \x01(\x05R\x06chunks\x12\x1a\n" +
	"\bembedded\x18\x03 \x01(\x05R\bembedded\x12&\n" +
	"\x06status\x18\x04 \x01(\v2\x0e.ash.v1.StatusR\x06status\"\xbd\x01\n" +
	"\fQueryRequest\x12.\n" +
	"\acontext\x18\x01 \x01(\v2\x14.ash.v1.TraceContextR\acontext\x12\x1b\n" +
	"\trepo_root\x18\x02 \x01(\tR\brepoRoot\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\x12\x16\n" +
	"\x06prefer\x18\x05 \x01(\tR\x06prefer\x12\x1f\n" +
	"\vexpand_refs\x18\x06 \x01(\bR\n" +
	"expandRefs\"\xca\x01\n" +
	"\bQueryHit\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"start_line\x18\x04 \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\x05 \x01(\x05R\aendLine\x12\x16\n" +
	"\x06digest\x18\x06 \x01(\tR\x06digest\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\x12\x18\n" +
	"\asnippet\x18\b \x01(\tR\asnippet\"\xa6\x02\n" +
	"\rQueryResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.ash.v1.QueryHitR\x05items\x12%\n" +
	"\x0eretrieval_mode\x18\x02 \x01(\tR\rretrievalMode\x12#\n" +
	"\rfts_available\x18\x03 \x01(\bR\fftsAvailable\x12)\n" +
	"\x10vector_available\x18\x04 \x01(\bR\x0fvectorAvailable\x12'\n" +
	"\x0fvector_fallback\x18\x05 \x01(\tR\x0evectorFallback\x12%\n" +
	"\x0eprefer_applied\x18\x06 \x01(\tR\rpreferApplied\x12&\n" +
	"\x06status\x18\a \x01(\v2\x0e.ash.v1.StatusR\x06status2\x8b\x01\n" +
	"\x11RagIndexerService\x12@\n" +
	"\tIndexRepo\x12\x18.ash.v1.IndexRepoRequest\x1a\x19.ash.v1.IndexRepoResponse\x124\n" +
	"\x05Query\x12\x14.ash.v1.QueryRequest\x1a\x15.ash.v1.QueryResponseB/Z-github.com/ash-repwiki/ash/proto/ash/v1;ashv1b\x06proto3"

var (
	file_ash_v1_rag_indexer_proto_rawDescOnce sync.Once
	file_ash_v1_rag_indexer_proto_rawDescData []byte
)

func file_ash_v1_rag_indexer_proto_rawDescGZIP() []byte {
	file_ash_v1_rag_indexer_proto_rawDescOnce.Do(func() {
		file_ash_v1_rag_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ash_v1_rag_indexer_proto_rawDesc), len(file_ash_v1_rag_indexer_proto_rawDesc)))
	})
	return file_ash_v1_rag_indexer_proto_rawDescData
}

var file_ash_v1_rag_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ash_v1_rag_indexer_proto_goTypes = []any{
	(*IndexRepoRequest)(nil),  // 0: ash.v1.IndexRepoRequest
	(*IndexRepoResponse)(nil), // 1: ash.v1.IndexRepoResponse
	(*QueryRequest)(nil),      // 2: ash.v1.QueryRequest
	(*QueryHit)(nil),          // 3: ash.v1.QueryHit
	(*QueryResponse)(nil),     // 4: ash.v1.QueryResponse
	(*TraceContext)(nil),      // 5: ash.v1.TraceContext
	(*Status)(nil),            // 6: ash.v1.Status
}
var file_ash_v1_rag_indexer_proto_depIdxs = []int32{
	5, // 0: ash.v1.IndexRepoRequest.context:type_name -> ash.v1.TraceContext
	6, // 1: ash.v1.IndexRepoResponse.status:type_name -> ash.v1.Status
	5, // 2: ash.v1.QueryRequest.context:type_name -> ash.v1.TraceContext
	3, // 3: ash.v1.QueryResponse.items:type_name -> ash.v1.QueryHit
	6, // 4: ash.v1.QueryResponse.status:type_name -> ash.v1.Status
	0, // 5: ash.v1.RagIndexerService.IndexRepo:input_type -> ash.v1.IndexRepoRequest
	2, // 6: ash.v1.RagIndexerService.Query:input_type -> ash.v1.QueryRequest
	1, // 7: ash.v1.RagIndexerService.IndexRepo:output_type -> ash.v1.IndexRepoResponse
	4, // 8: ash.v1.RagIndexerService.Query:output_type -> ash.v1.QueryResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ash_v1_rag_indexer_proto_init() }
func file_ash_v1_rag_indexer_proto_init() {
	if File_ash_v1_rag_indexer_proto != nil {
		return
	}
	file_ash_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ash_v1_rag_indexer_proto_rawDesc), len(file_ash_v1_rag_indexer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ash_v1_rag_indexer_proto_goTypes,
		DependencyIndexes: file_ash_v1_rag_indexer_proto_depIdxs,
		MessageInfos:      file_ash_v1_rag_indexer_proto_msgTypes,
	}.Build()
	File_ash_v1_rag_indexer_proto = out.File
	file_ash_v1_rag_indexer_proto_goTypes = nil
	file_ash_v1_rag_indexer_proto_depIdxs = nil
}
