// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ash/v1/rag_indexer.proto

package ashv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RagIndexerService_IndexRepo_FullMethodName = "/ash.v1.RagIndexerService/IndexRepo"
	RagIndexerService_Query_FullMethodName     = "/ash.v1.RagIndexerService/Query"
)

// RagIndexerServiceClient is the client API for RagIndexerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RagIndexerService is the Stage-1 in-process / optional loopback indexer contract (DX75).
// Production default: no listen until ASH_RAG_INDEXER_GRPC_ADDR is set (DX76).
type RagIndexerServiceClient interface {
	IndexRepo(ctx context.Context, in *IndexRepoRequest, opts ...grpc.CallOption) (*IndexRepoResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type ragIndexerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRagIndexerServiceClient(cc grpc.ClientConnInterface) RagIndexerServiceClient {
	return &ragIndexerServiceClient{cc}
}

func (c *ragIndexerServiceClient) IndexRepo(ctx context.Context, in *IndexRepoRequest, opts ...grpc.CallOption) (*IndexRepoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexRepoResponse)
	err := c.cc.Invoke(ctx, RagIndexerService_IndexRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragIndexerServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, RagIndexerService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagIndexerServiceServer is the server API for RagIndexerService service.
// All implementations should embed UnimplementedRagIndexerServiceServer
// for forward compatibility.
//
// RagIndexerService is the Stage-1 in-process / optional loopback indexer contract (DX75).
// Production default: no listen until ASH_RAG_INDEXER_GRPC_ADDR is set (DX76).
type RagIndexerServiceServer interface {
	IndexRepo(context.Context, *IndexRepoRequest) (*IndexRepoResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
}

// UnimplementedRagIndexerServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRagIndexerServiceServer struct{}

func (UnimplementedRagIndexerServiceServer) IndexRepo(context.Context, *IndexRepoRequest) (*IndexRepoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexRepo not implemented")
}
func (UnimplementedRagIndexerServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedRagIndexerServiceServer) testEmbeddedByValue() {}

// UnsafeRagIndexerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagIndexerServiceServer will
// result in compilation errors.
type UnsafeRagIndexerServiceServer interface {
	mustEmbedUnimplementedRagIndexerServiceServer()
}

func RegisterRagIndexerServiceServer(s grpc.ServiceRegistrar, srv RagIndexerServiceServer) {
	// If the following call pancis, it indicates UnimplementedRagIndexerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RagIndexerService_ServiceDesc, srv)
}

func _RagIndexerService_IndexRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagIndexerServiceServer).IndexRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagIndexerService_IndexRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagIndexerServiceServer).IndexRepo(ctx, req.(*IndexRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagIndexerService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagIndexerServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagIndexerService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagIndexerServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RagIndexerService_ServiceDesc is the grpc.ServiceDesc for RagIndexerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RagIndexerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ash.v1.RagIndexerService",
	HandlerType: (*RagIndexerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndexRepo",
			Handler:    _RagIndexerService_IndexRepo_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _RagIndexerService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ash/v1/rag_indexer.proto",
}
